[versions]
agp = "8.13.1"
androidxAppcompat = "1.6.1"
androidxConstraintlayout = "2.1.4"
androidxJunit = "1.1.3"
appcompatVersion = "1.4.0"
constraintlayoutVersion = "2.1.2"
espressoCoreVersion = "3.4.0"
googleMaterial = "1.9.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
lifecycleLivedata = "2.10.0"
material = "1.13.0"
activity = "1.8.0"
constraintlayout = "2.2.1"
firebaseCrashlyticsBuildtools = "3.0.6"
materialVersion = "1.4.0"
navigationFragment = "2.4.2"
navigationUi = "2.9.6"
navigationUiVersion = "2.4.2"

[libraries]
appcompat-v140 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
constraintlayout-v212 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
constraintlayout-v214 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintlayout" }
espresso-core-v340 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-v113 = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycleLivedata" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
material-v140 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
material-v190 = { module = "com.google.android.material:material", version.ref = "googleMaterial" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationUi" }
navigation-fragment-v242 = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationUi" }
navigation-ui-v242 = { module = "androidx.navigation:navigation-ui", version.ref = "navigationUiVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

